# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.x.x'

    - name: dotnet - restore
      run: dotnet restore
  
    - name: dotnet - build
      run: dotnet build --no-restore

    # - name: dotnet - test
    #   run: dotnet test --no-build --verbosity normal
