# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish to Nuget

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.1.0
        with:
          versionSpec: "6.x.x"

      - name: Set Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v4.1.0
        with:
          updateProjectFiles: true

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.x.x"

      - name: dotnet - restore
        run: dotnet restore

      - name: dotnet - format
        run: dotnet format --verify-no-changes

      - name: dotnet - pack
        run: dotnet pack --no-restore

      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: NuGet push
        run: dotnet nuget push **/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
